### ISSUE TITLE
Do we prompt the user for input? Absolutely

### ISSUE THREAD

**Issue by tanyaraja** [ubccsss/codingCompetition2020#4]
Hi! I was wondering if for Absolutely we have to ask the user for an array, or if you will test our code by inputting your desired array into the code directly. Thanks!

**Comment by natchensing** [comment]
You can test by inputting your array directly as an input.

**Comment by tanyaraja** [comment]
Just to clarify - our code then does not have to prompt the user for an input when it is run. Correct?

**Comment by natchensing** [comment]
Correct.
