### ISSUE TITLE
Array inputs

### ISSUE THREAD

**Issue by brookedai** [ubccsss/codingCompetition2020#5]
For inputs such as the ones in TheMazeRunner, eg.
`blocked = [[0,1],[1,1],[2,0],[2,1]], source = [1,0], target = [0,2]`
will they be given exactly like this (with [])? Or could we change it to be something like
4
0 1
1 1
2 0
2 1
1 0
0 2

**Comment by natchensing** [comment]
Unfortunately no, blocked, source, and target must be separate variables
