### ISSUE TITLE
Sausage not on pizza counted? Ohno

### ISSUE THREAD

**Issue by tanyaraja** [ubccsss/codingCompetition2020#9]
Hi! 

For sausages that are not on the pizza (i.e., do not fit in R) - do they count to pizzas stuck on the crust?

**Comment by natchensing** [comment]
Your sausage can be on the pizza main part (within R) or on the crust or both. We want you to give  the number of sausage completely on the crust.

**Comment by tanyaraja** [comment]
Yep! I get that. 

However, for the example provided (I also might have calculated wrong):
8 4 7 7 8 1 -7 3 2 0 2 1 0 -2 2 -3 -3 1 0 6 2 5 3 1

the first sausage is at the location (7,8) with r = 1. 
The sausage is then at a distance of  ~ 10.63 from the center, which is greater than R (and 10.63 +/- r is > R). So I assume it's not ON the pizza at all?

**Comment by tanyaraja** [comment]
And if it isn't ON the pizza, then I also do not count it to be stuck on the crust - correct? 

Sorry for so many questions and thank you so much :))))

**Comment by natchensing** [comment]
The total pizza radius would be 8+4 for this example. So technically the sausage is still ON the pizza, just on the pizza crust since the crust is an extra 4 units more.

**Comment by tanyaraja** [comment]
"The pizza is a circle of radius R centered on the origin. Pizza consists of the main part — circle of radius R - D with center at the origin, and crust around the main part of the width D. "

This means that the entire pizza is of radius R of which the main part (not crust) is of the radius (R-D). So I don't understand how does pizza + crust = R+D?  :(

**Comment by natchensing** [comment]
Sorry that was a misread from my part. Let me double check with the other mods.

**Comment by rzhang404** [comment]
Your guess is correct-- sausage not on the pizza, or even partially hanging off the pizza, is not regarded as being "entirely on the crust". I mean I personally wouldn't mind a couple extra slices just sitting in the box.

**Comment by tanyaraja** [comment]
Lmao me neither. 

Thanks guys!!
